import sqlite3
import os
import pandas as pd

from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle
)

from reportlab.lib import colors

DATABASE = "database/filemonitor.db"

REPORT_FOLDER = "reports"

os.makedirs(REPORT_FOLDER, exist_ok=True)


def fetch_data():

    conn = sqlite3.connect(DATABASE)

    df = pd.read_sql_query(
        "SELECT * FROM file_events",
        conn
    )

    conn.close()

    return df


# ----------------------------------------
# Excel
# ----------------------------------------

def generate_excel():

    df = fetch_data()

    filepath = os.path.join(
        REPORT_FOLDER,
        "Audit_Report.xlsx"
    )

    df.to_excel(
        filepath,
        index=False
    )

    return filepath


# ----------------------------------------
# CSV
# ----------------------------------------

def generate_csv():

    df = fetch_data()

    filepath = os.path.join(
        REPORT_FOLDER,
        "Audit_Report.csv"
    )

    df.to_csv(
        filepath,
        index=False
    )

    return filepath


# ----------------------------------------
# PDF
# ----------------------------------------

def generate_pdf():

    from reportlab.platypus import (
        SimpleDocTemplate,
        Table,
        TableStyle,
        Paragraph,
        Spacer
    )

    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib import colors
    from datetime import datetime

    df = fetch_data()

    filepath = os.path.join(
        REPORT_FOLDER,
        "Audit_Report.pdf"
    )

    doc = SimpleDocTemplate(filepath)

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    story = []

    # --------------------------
    # Title
    # --------------------------

    story.append(
        Paragraph(
            "Secure File Transfer Monitoring System",
            title
        )
    )

    story.append(
        Paragraph(
            "Security Audit Report",
            heading
        )
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now()}",
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>Generated By:</b> Administrator",
            normal
        )
    )

    story.append(Spacer(1,20))

    # --------------------------
    # Summary
    # --------------------------

    total = len(df)

    created = len(df[df["event_type"]=="Created"])
    modified = len(df[df["event_type"]=="Modified"])
    deleted = len(df[df["event_type"]=="Deleted"])
    moved = len(df[df["event_type"]=="Moved"])

    summary = [

        ["Metric","Value"],

        ["Total Events",total],

        ["Created",created],

        ["Modified",modified],

        ["Deleted",deleted],

        ["Moved",moved]

    ]

    table = Table(summary)

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("GRID",(0,0),(-1,-1),1,colors.black),

        ("BACKGROUND",(0,1),(-1,-1),colors.beige),

        ("BOTTOMPADDING",(0,0),(-1,0),10)

    ]))

    story.append(table)

    story.append(Spacer(1,25))

    story.append(
        Paragraph(
            "<b>Recent File Monitoring Events</b>",
            heading
        )
    )

    story.append(Spacer(1,10))

    # --------------------------
    # Recent Events
    # --------------------------

    recent = df.tail(20)

    data = [

        [
            "Time",
            "Event",
            "File",
            "User",
            "Status"
        ]

    ]

    for _, row in recent.iterrows():

        data.append([

            str(row["timestamp"]),

            row["event_type"],

            row["file_name"],

            row["username"],

            row["status"]

        ])

    table2 = Table(data)

    table2.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),colors.darkgreen),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("GRID",(0,0),(-1,-1),1,colors.black),

        ("FONTSIZE",(0,0),(-1,-1),8),

        ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke)

    ]))

    story.append(table2)

    doc.build(story)

    return filepath
